config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions:      "users/sessions",
  }

  namespace :users do
    authenticate :user do
      resources :connections, only: [:index, :create, :update, :destroy]
      resources :accounts, only: [:index]
      resources :transactions, only: [:index]
    end
  end

  namespace :api do
    resources :connections,  only: [:index, :show, :update, :destroy]
    resources :accounts,     only: :index
    resources :transactions, only: :index
  end

  root "users/connections#index"
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Presentation
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body.container
    - if current_user
      %h3= link_to "User", users_connections_path
      %code
        %b= "Shard: "
        = user_shard
      %br
      %code
        %b= "Email: "
        = current_user.email
      %br
      %code
        %b= "App-Id: "
        = current_user.app_id
      %br
      %code
        %b= "Secret: "
        = current_user.secret
      %br
      %br
      = button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-warning"
      %hr
    = yield

    = content_tag(:div, flash[:error],  :class => "alert alert-danger") if flash[:error]
    = content_tag(:div, flash[:notice], :class => "alert alert-info")   if flash[:notice]
    - flash.clear